Multas/Multas/Models/Agentes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Multas.Models
{
    public class Agentes
    {
        public Agentes()
        {
            ListaDeMultas = new HashSet<Multas>();
        }
        [Key]
        [DatabaseGenerated()]
        public int ID { get; set; }
        [Required(ErrorMessage ="O {0} é de preenchimento obrigatório")]
        [RegularExpression("[A-ZÁÉÍÓÚÀÈÌÒÙÂÊîÔÛ][a-záéíóúàèìòùâêîôûãõç]+ (( |’|-| dos | da | de| e | d’)[A-ZÁÉÍÓÚÀÈÌÒÙÂÊîÔÛ][a-záéíóúàèìòùâêîôûãõç]+){1,3})", ErrorMessage = "Não válido")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "A {0} é de preenchimento obrigatório")]
        [RegularExpression("[A-ZÁÉÍÓÚÀÈÌÒÙÂÊîÔÛ]*[a-záéíóúàèìòùâêîôûãõç]*", ErrorMessage = "Não válido")]
        public string Esquadra { get; set; }

        public string Fotografia { get; set; }
        //lista de objetos que este atributo vai ter como chave forasteira
        //referência ás multas que um agente emite 
        public virtual ICollection<Multas> ListaDeMultas { get; set; }

        //nome do login (UserName) utilizado pelo agente
        //na prática, ´´e uma FK para a tabela dos utilizadores 
       // [Required]
        public string UserName { get; set; }
    }
}

Multas/Multas/Controllers/AgentesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Multas.Models;

namespace Multas.Controllers
{
    [Authorize(Roles = "Agentes, GestaoDePessoal")]
    //tem premissao de acesso quem for agente ou gestaodepessoaç
    public class AgentesController : Controller
    {
        //cria uma variável
        
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Agentes
        /// <summary>
        /// lista todos os agente 
        /// </summary>
        /// <returns></returns>
        
        public ActionResult Index()
        {
            //db.Agentes.ToList() -> em sql: SELECT * FROM Agentes;
            //enviar para a View uma lista com todos os agente da base de dados 

            //recuperar os dados pessoais de uma pessoa que se autenticou 
            //var dadosPessoais = db.Users.Find(User.Identity.GetUserId());
            
            var dadosPessoais = db.Utilizadores.Where(u => u.NomeRegistoDoUtilizador.Equals(User.Identity.Name)).FirstOrDefault();
            //FirstOrDfault para retornar um elemento unico, sem este comando retornaria uma lista
            //agora, com este objeto, já posso utilizar
            //os dados pessoais de um utilizador no meu programa 
            //por exemplo
            Session["nomeUtilizador"] = dadosPessoais.NomeProprio + "" + dadosPessoais.Apelido;


            //obter a lista de todos os agente 
            //em SQL: Select * from Agentes order by nome
            var listaDeAgentes =db.Agentes.OrderBy(a=>a.Nome).ToList();

            return View(listaDeAgentes);
        }

        // GET: Agentes/Details/5
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            //int? preenchimento facultativo (em sql contrário de NOT NULL)
            //proteção para caso de não ter sido fornecido um ID valido
            if (id == null)
            {   //instrução original
                //devolve um erro quando não há id, logo não é possível pesquisar por um agente 
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                //redirecionar para uma página que seja controlável
                return RedirectToAction("Index");
            }
            //procura na BD, o Agente cujo ID for fornecido
            Agentes agente = db.Agentes.Find(id);
            //proteção para caso não se ter encontrado o Aagente que tenha o ID fornecido
            if (agente == null)
            {
                //o agente não foi encontrado logo, gera-se uma mensagem de erro
                //return HttpNotFound();

                //redirecionar para uma página que seja controlável
                return RedirectToAction("Index");

            }
            //fazer a mesma proteção que foi feita no EDIT (GET)
            //entrega á View os dados do Agente encontrado 
            return View(agente);
        }

        // GET: Agentes/Create
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = " GestaoDePessoal")]
        //Neste método, apenas o GestaoDePessoal pode criar 
        public ActionResult Create()
            //apresneta a View para se inserir um novo agente
        {
            return View();
        }

        // POST: Agentes/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// 
        /// </summary>
        /// <param name="agente"></param>
        /// <param name="uploadFotografia"></param>
        /// <returns></returns>
        //anotador para HTTP POST
        [HttpPost]
        //anortador para proteção por roube de identidade
        [ValidateAntiForgeryToken]
        [Authorize(Roles = " GestaoDePessoal")]
        public ActionResult Create([Bind(Include = "Nome,Esquadra")] Agentes agente, HttpPostedFileBase uploadFotografia) {
            //agente - parametro de entrada
            //include -  dados que vêm da view

            //escrever os dados de um novo Agente na BD
            //especificar o ID do novo Agente
            //testar s ehá resgistos na tabela dos Agentes (count - devolve o número de registos) 
            //if (db.Agentes.Count() != 0) {}
            //ou entã, usar a instrução Try/Catch
            int idNovoAgente = 0;
            try
            {
                idNovoAgente = db.Agentes.Max(a => a.ID) + 1;
            }
            catch (Exception) {
                idNovoAgente = 1;
            }
               
            //guardar o ID do novo Agente
            agente.ID = idNovoAgente;
            //Especificar (escolher) o nome do ficheiro
             string nomeImagem = "Agente_"+idNovoAgente + ".jpg";
            //var auxiliar
            string path = "";
            //validar se a imagem foi fornecida
            if (uploadFotografia != null)
            {
                //o ficheiro foi fornecido 
                //Validar se o que foi fornecido é uma imagem 
                //formatar o tamanho da imagem

                //criar o caminho completo até ao sítio onde o ficheiro será guardado
                path = Path.Combine(Server.MapPath("~imagens/"), nomeImagem + ".jpg");

                //guardar o nome do ficheiro 
                agente.Fotografia = nomeImagem;


            }
            else {
                //não foi fornecido qualquer ficheiro 
                //gerar uma mensagem de erro
                ModelState.AddModelError("", "Não foi fornecida nenhuma imagem...");
                //devolver o controlo á View 
                return View(agente);

            }
            //escrever o ficheiro com a fotografia no disco rígido, na pasta 'imagens'
            //guardar o nome escolhido na BD

            //ModelState.IsValid -> 
            //adiciona o novoconfronta os dados fornecidos da View com as exigências do Modelo              
            if (ModelState.IsValid)
            {
                try
                {
                    //adiciona o novo agente á BD
                    db.Agentes.Add(agente);
                    //faz 'Commit' às alterações 
                    db.SaveChanges();
                    //redireciona para a pagina de Index
                    //escrever o ficheiro 
             
                    //se tudo coorer bem, redireciona para a pagina de index
                    return RedirectToAction("Index");
                }
                catch (Exception ex) {
                    //ModelState-objecto que identifica o modelo 
                    ModelState.AddModelError("", "Houve um erro com a criação do novo agente... ");

                    ///se existir uma classe chamada 'Erros.cs'
                    ///iremos nela registar os dados do erro 
                    ///-cirar um objeto desta classe
                    ///-atribuir a esse objeto os dados do erro
                    ///     -nome do controller
                    ///     -nome do método
                    ///     -data + hora do erro 
                    ///     - mensagem do erro (ex)
                    ///     -dados que se tentavam inserir 
                    ///     -outros dados considerados relevantes 
                    /// -guardar o objeto na BD
                    /// -notificar um gestor do sistema, por email, ou por outro meio do erro e dos seus dados
                    
                }
            }
            //se houver um erro, representa os dados do Agente na View
            return View(agente);
        }

        // GET: Agentes/Edit/5
        /// <summary>
        /// apresentar na view os dados de um agente para 
        /// eventual edição
        /// </summary>
        /// <param name="id">identifica o agente a editar </param>
        /// <returns>view</returns>
        public ActionResult Edit(int? id)
        {
            //int? preenchimento facultativo (em sql contrário de NOT NULL)
            //proteção para caso de não ter sido fornecido um ID valido
            if (id == null)
            {   //instrução original
                //devolve um erro quando não há id, logo não é possível pesquisar por um agente 
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                //redirecionar para uma página que seja controlável
                return RedirectToAction("Index");
            }
            //procura na BD, o Agente cujo ID for fornecido
            Agentes agente = db.Agentes.Find(id);
            //proteção para caso não se ter encontrado o Aagente que tenha o ID fornecido
            if (agente == null)
            {
                //o agente não foi encontrado logo, gera-se uma mensagem de erro
                //return HttpNotFound();

                //redirecionar para uma página que seja controlável
                return RedirectToAction("Index");

            }
            //existe agente 
            //contudo, será que posso editá-lo
            if (User.IsInRole("GestaoDePessoal") || User.Identity.Name.Equals(agente.UserName))
            {
                //entrega á View os dados do Agente encontrado 
                return View(agente);
            }
            else
            {
                //não ha permissão para editar o Agente 
                return RedirectToAction("Index");

            }
        }

        // POST: Agentes/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>

Multas/Multas/Views/Agentes/Create.cshtml
@model Multas.Models.Agentes

@{
    ViewBag.Title = "Create";
    <h2
    }

    <h2>Adicionar Novo Agente</h2>


    @using (Html.BeginForm("Create", "Agentes", FormMethod.Post, new { enctype = "multipart/form-data" }))
    //reponsável pela criação do formulário, não envia só texto mas também envia dados
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>Agentes</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Esquadra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Esquadra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Esquadra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*Adição do objeto para fazer o file upload de uma fotografia*@
                @*@Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="uploadFotografia" style="color:blue;" accept=".jpg"
                       @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
    @Html.ActionLink("Regressar", "Index")
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Multas/Multas/Views/Agentes/Delete.cshtml
@model Multas.Models.Agentes

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Quer mesmo apagar este Agente?</h3>
<div>
    <h4>Agentes</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Esquadra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Esquadra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fotografia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fotografia)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="btn btn-default" /> |
            @Html.ActionLink("Regressar á Lista", "Index")
        </div>
    }
</div>

Multas/Multas/Views/Agentes/Details.cshtml
@model Multas.Models.Agentes

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Agentes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Esquadra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Esquadra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fotografia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fotografia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Multas/Multas/Views/Agentes/Edit.cshtml
@model Multas.Models.Agentes

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Agentes</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.UserName)

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Esquadra, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @if (User.IsInRole("GestaoDePessoal"))
            {
                <text>
                    @Html.EditorFor(model => model.Esquadra, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Esquadra, "", new { @class = "text-danger" })
                </text>
            }
            else
            {
                @Html.EditorFor(model => model.Esquadra, new { htmlAttributes = new { @class = "form-control" } })

            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<a href="~/Views/_ViewStart.cshtml">~/Views/_ViewStart.cshtml</a>

Multas/Multas/Views/Agentes/Index.cshtml
@model IEnumerable<Multas.Models.Agentes>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@if(User.IsInRole("GestorDePessoal"))
<p>
    @Html.ActionLink("Criar Novo Agente", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome) @* model => model.Nome --> espressão Labda*@
            
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Esquadra)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fotografia)
        </th>
        <th></th>
    </tr>
    @*item-agente, model-lista de agentes*@
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Esquadra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fotografia)
            <a href="~/imagens/@item.Fotografia" target="_blank">
                <img src="~/imagens/@item.Fotografia" width="50" height="37" />
            </a>
        </td>
        <td>
            @if (User.IsInRole("GestaoDePessoal"))
    {
        @*links de acesso a editar, detalhes e apagar*@
        <text>
            @Html.ActionLink("Editar", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Detalhes", "Details", new { id = item.ID }) |
            @Html.ActionLink("Apagar", "Delete", new { id = item.ID })
        </text>
        @*o bloco text, serve para colocar tudo no mesmo if*@
}
else
{
        @*Os links vão ser acedidos dependedo do user que tem o login feito
            se a tania tiver o login feito, apenas poderá alterar os dados da tania*@
        if (User.Identity.Name.Equals(agente.Username)
{
        <text>
            @Html.ActionLink("Editar", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Detalhes", "Details", new { id = item.ID }) |
            @Html.ActionLink("Apagar", "Delete", new { id = item.ID })
        </text>


}


}
        </td>
    </tr>
}

</table>